In [7]:
import numpy as np
my_list = [ 10 , 20 , 30 , 40 , 50 ]
a = np.array (my_list)
print(my_list)
print(a)

[10, 20, 30, 40, 50]
[10 20 30 40 50]


In [11]:
import numpy as np
my_list = [ 1 , 2 , 3 , 4 , 5 ]
b = np.array(my_list)
print(b)

[1 2 3 4 5]


In [29]:
a = np.array ([ 10 , 20 , 30 , 40 , 50 ])
b = np.array([ 1 , 2 , 3 , 4 , 5 ])
dot_product = sum( a * b )
reshape_array = a.reshape( 5 , 1 )
print ( a + b )
print ( a - b )
print ( a * b )
print ( a / b )
print ( a.min())
print ( a.max())
print (dot_product)
print(reshape_array)



[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
10
50
550
[[10]
 [20]
 [30]
 [40]
 [50]]
